name: Test project mutual dependency versions

# run CI on pushes to master, and on all PRs (even the ones that target other
# branches)

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.x']
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: check dependencies
        run: yarn depcheck
